### PR TITLE
Fix for cryptography library dependency

### PR DESCRIPTION
**Pull request by lifehackjim**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
related: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

### CODE REVIEW

**Comment by glicht** [comment]
@lifehackjim thanks for your contribution. Do you want to also updated the version of `axonius_api_client`?

**Comment by lifehackjim** [comment]
> @lifehackjim thanks for your contribution. Do you want to also updated the version of `axonius_api_client`?

Actually, yes - thank you for reminding me.

Is it permitted for me to do axonius-api-client = "==4.*" in your Pipfiles?

**Comment by lifehackjim** [comment]
I switched from using pipenv to normal requirements.txt since pipenv is centered around locking to specific versions where I want the latest minor or micro release of the v4 major version

**Comment by glicht** [comment]
@lifehackjim No problem to use Pipenv to limit to 4.x. I've opened a separate PR for this: https://github.com/demisto/dockerfiles/pull/3678. We will manage the update in that PR. Also we've updated the base Crypto image, so no need for changes in the dev dependencies.

**Comment by glicht** [comment]
Closing as this has been updated in https://github.com/demisto/dockerfiles/pull/3678

**Pull request closed without merging**
