### PR TITLE
Python base version updated in the Dockerfile.

### PR DESCRIPTION
**Pull request by sriram7797**
## Status
Ready

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
Related: Security fixes for vulnerability.

## Description
Base python version has been updated in the Dockerfile for security vulnerability fixes.

### CODE REVIEW

**Comment by kgal-pan** [comment]
@sriram7797 - Can you please add a verify script? See https://github.com/demisto/dockerfiles/blob/master/README.md#adding-a-verifypy-script.

Also, please sign the [CLA agreement](https://cla-assistant.io/demisto/dockerfiles?pullRequest=22137).

**Comment by kgal-pan** [comment]
From what I see, the build is failing because it can't find a license for the `accessdata-sdk` package.  

I was able to find it in https://api.github.com/repos/AccessDataOps/FTK-API-SDK/license. 

Checking.

**Comment by sriram7797** [comment]
@kgal-pan i have signed CLA agreement. No changes were made on SDK, it's just an python version upgrade (py 3.9 to py 3.10) in the Dockerfile. Any changes that needs to be done on my end for build issues?

**Comment by kbbgl** [comment]
>  Any changes that needs to be done on my end for build issues?

Please add the verify script.

**Comment by kgal-pan** [comment]
> Any changes that needs to be done on my end for build issues?

Please [add a verify script as previously requested](https://github.com/demisto/dockerfiles/pull/22137#issuecomment-1824520997).

**Comment by kgal-pan** [comment]
> From what I see, the build is failing because it can't find a license for the `accessdata-sdk` package.
> 
> I was able to find it in https://api.github.com/repos/AccessDataOps/FTK-API-SDK/license.
> 
> Checking.

**UPDATE**

@sriram7797 -

Seems that this issue is not related to the license but to a failure when setting up the virtual environment and installing dependencies. The [error we're seeing](https://github.com/AccessDataOps/FTK-API-SDK/blob/main/requirements.txt#L1) is because of a `>` sign when specifying the `python_version>=3.9` in the [AccessData `requirements.txt`](https://github.com/AccessDataOps/FTK-API-SDK/blob/main/requirements.txt#L1).

From what I see in https://pip.pypa.io/en/stable/reference/requirement-specifiers/#examples, the `python_version` version specifier is supposed to be added after the package with a semilcolon to separate them, e.g:

```ini
requests ; python_version >= '3.9'
```

**Comment by sriram7797** [comment]
@kgal-pan thanks for the inputs.. will add verify script and check on requirements.txt.. and update you..

**Comment by kgal-pan** [comment]
Looks like the issues with installing the `accessdata-sdk` package were resolved. Now the issue is the missing license (both in pypi and pip):

```bash
❯ pip show accessdata-sdk
Name: accessdata-sdk
Version: 0.7.0
Summary: Python Library for AccessData's API
Home-page: https://github.com/AccessDataOps/FTK-API-SDK
Author: Thomas Vieth
Author-email: thomas.vieth@exterro.com
License:
Location: /Users/kgal/.local/share/virtualenvs/accessdata-tfh4rtKR-python/lib/python3.11/site-packages
Requires: requests
Required-by:
```

@sriram7797 is looking into it.

**Review by JudahSchwartz — APPROVED** [review]
looks good!

**Pull request merged**
