### PR TITLE
New DomainTools Integration Docker Image

### PR DESCRIPTION
**Pull request by wesleya**
## Status
Ready

## Related Content Pull Request
N/A

## Related Issues
N/A

## Description
Create Docker image for use in DomainTools Integration

### CODE REVIEW

**Comment by wesleya** [comment]
Hi @eyalpalo! There is no content contribution PR to go along with this yet. We are starting work on an update to this pack: https://github.com/demisto/content/tree/master/Packs/DomainTools_Iris

Our plan was to get the dependencies added in this PR squared away before starting work on the corresponding updates to the DomainTools_Iris pack. Is that okay? Thank you!

**Comment by wesleya** [comment]
Hi @eyalpalo, I saw that I had a new failed workflow for `native_docker_image_labeled`.  I read through the [The Native Image Docker Validator](https://github.com/demisto/dockerfiles/blob/master/README.md#the-native-image-docker-validator-and-native-image-approved-label) docs but wasn't sure what I needed to update in my PR to get that passing. Do you have any further details on what I need to update? Or a link to an example of what's needed here?

I also saw that merging was blocked until I pulled in the latest from master, I pulled that in which hid the failed workflow. Here's a link to the failed job in case it helps: https://github.com/demisto/dockerfiles/actions/runs/5060142397/jobs/9210617269?pr=16869

**Comment by JudahSchwartz** [comment]
@wesleya hey, lets wait to merge this PR until the content PR is ready for merge, in case the docker will need to change for any reason
Regarding the failing workflow, you can ignore it for now. Seems like theres an issue with it. @YuvHayun could you check that out?

**Comment by JudahSchwartz** [comment]
@YuvHayun` the following dockers were updated: oauthlib, tidy, winrm, ami-management, xml-feed, py3-native, crypto, azure-kusto-data, oci, boto3py3, akamai, ansible-runner, ssl-analyze, taxii-server, keeper-ksm, google-api-py3, axonius, domaintools, pydantic-jwt3, pyjwt3, teams, flask-nginx, demisto-sdk, py3ews. Please consider updating their verify script accordingly.`
From verify check. Looks like they used a bad diff somehow (maybe related to the fact that its a  fork.)

**Pull request closed without merging**
