### PR TITLE
vendors-sdk - Update the packages

### PR DESCRIPTION
**Pull request by briluza**
## Status
Ready

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
Related: https://github.com/demisto/dockerfiles/pull/34782

## Description
updated `poetry.lock` file for `docker/vendors-sdk` to get the latest version of `domaintools-api`

### CODE REVIEW

**Review by samuelFain — CHANGES_REQUESTED** [review]
Hi @briluza and thank you for your contribution!
A few notes:
- Please add a description of what is purpose of this PR, what is changed etc..
- I see that only the `docker/vendors-sdk/poetry.lock` file has changed in this PR. However, changes to the poetry.lock file typically result from modifications to the `pyproject.toml` file, followed by running a command like `poetry lock`. I feel like the changes to the pyproject.toml are missing in this PR, unless this was intentional and you the aim was to generally update the dependencies of this docker image. Please let me know if I am misunderstanding your intentions.
- Generally, contributions to the dockerfiles repository are accompanied by a corresponding PR in the content repository. While this is not mandatory, if there is a related PR in the content repository, please let me know about it.

**Comment by briluza** [comment]
Hi @samuelFain, 

thank you for the quick response, in this PR I only update the `poetry.lock` as mostly the packages (including the `domaintools-api`) has the version in the `pyproject.toml` is set to `*` , I think I just need to update the lock file and not the toml file to update the packages/dependencies. (correct me if I'm wrong) 

- for the PR related, as of the moment No we haven't raised the PR in the `content` repo as it's still in progress and this package update is needed so we can test it in our dev and staging environment.

Let me know if I missed something or I need to change anything. Thank you!

**Comment by samuelFain** [comment]
@briluza Everything looks good to me then.
Just a quick note: due to a technical issue we are currently experiencing, the 
`ci/gitlab/gitlab.xdr.pan.local` and `native_docker_image_labeled` GitHub actions cannot run on a contribution PR to the dockerfiles repository - like this one. This is a merge blocker.
To save us all the waiting time, I went ahead and opened an [internal PR ](https://github.com/demisto/dockerfiles/pull/34782) with the changes of this PR so I can merge it.
This will mean that I'll merge the internal PR with the changes from this PR instead of merging this PR.
Please let me know if you are OK with this action, and if you do, please verify the changes in https://github.com/demisto/dockerfiles/pull/34782 and let me know we are good-to-merge.

**Comment by briluza** [comment]
I checked and verify that the changes in poetry.lock also updates the `domaintools-api` package in the latest version. Thank you!

**Comment by samuelFain** [comment]
Internal PR merged. Closing this PR.

**Pull request closed without merging**
