### PR TITLE
signal-cli image

### PR DESCRIPTION
**Pull request by glicht**
## Status
Ready

## Related Issues
related: link to the issue

## Description
In image with singal-cli

@aburt-demisto @Hruuttila FYI

### CODE REVIEW

**Comment by glicht** [comment]
@aburt-demisto @Hruuttila any updates?

**Comment by Hruuttila** [comment]
@glicht The docker image works as expected. Thank You. I am still investigating that can we actually use this approach after all as some of the commands in the signal-cli wait for action until they are finished. (like linking an existing phone number to the signal-cli client).

**Comment by glicht** [comment]
@Hruuttila @aburt-demisto any update regarding your tests?

**Comment by Hruuttila** [comment]
No update on this on my part. After initial research the signal cli logging in mechanism proved to be out of my skills to convert to feasible in XSOAR.

**Comment by glicht** [comment]
Closing for now

**Pull request closed without merging**
