### PR TITLE
Sane doc reports -> public

### PR DESCRIPTION
**Pull request by agamm**
## Status
In Progress

## Related Content Pull Request
demisto/sane-doc-reports#87

## Related Issues
Related: demisto/etc#37148

## Description
Make changes to add the public repo of sane-doc-reports & update a fix.

### CODE REVIEW

**Review by glicht — CHANGES_REQUESTED** [review]
Please change to use pipenv instead of `git clone`. Do the following in the dir `docker/sane-doc-reports`:
```
pipenv install  -e 'git+https://github.com/demisto/sane-doc-reports.git@master#egg=sane-doc-reports'
```
This will modify the Pipenv and Pipenv.lock files to install from github. Furthermore, the lock file will point to a specific commit. Then remove the `git clone` part in Dockerfile.

**Comment by glicht** [comment]
@agamm see my commit

**Comment by agamm** [comment]
> @agamm see my commit

Looks good, but it still doesn't use pipenv, right?

Plus, shouldn't the base image for python include: `gcc` and `python3-dev` ?

**Comment by agamm** [comment]
Let's merge?

**Review by glicht — APPROVED** [review]

**Pull request merged**
