### PR TITLE
added py-ews docker and updated dependencies

### PR DESCRIPTION
**Pull request by jochman**

### CODE REVIEW

**Comment by glicht** [comment]
Use `demisto/powershell-core` as a base.

**Comment by glicht** [comment]
Please also rename the `dockerfile` to `Dockerfile` (capital D).

**Comment by glicht** [comment]
@jochman any update?

**Comment by jochman** [comment]
> @jochman any update?

just got back from reserve duty. I've got a problem with c libraries when trying to merge dependencies, working on it.

**Pull request closed without merging**
