### PR TITLE
cloaken docker update; add response_status to return data

### PR DESCRIPTION
**Pull request by ajcypherint**

### CODE REVIEW

**Comment by glicht** [comment]
Nothing is being updated except the version. Don't really see why it is needed.

**Comment by ajcypherint** [comment]
I need the docker image rebuilt. I made a change to cloakensdk. Is there
another way to do this? Or do these all rebuild nightly?

**Comment by glicht** [comment]
You need to run: `pipenv update` in the `cloaken` directory. 

This will update the Pipfile.lock file with the latest package versions. Then commit this file.

**Comment by ajcypherint** [comment]
Thank you!

**Comment by glicht** [comment]
Are you pushing another commit of Pipfile.lock?

**Comment by ajcypherint** [comment]
Yes will do tonight.

**Comment by ajcypherint** [comment]
Ok I updated the Pipfile.lock with the latest version of CloakenSDK

**Pull request merged**
