### PR TITLE
Genericsql - including Microsoft sql

### PR DESCRIPTION
**Pull request by ohaim1008**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
related: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

### CODE REVIEW

**Comment by ohaim1008** [comment]
PR still in progress.

**Comment by glicht** [comment]
Please add a verify.py file. See: https://github.com/demisto/dockerfiles#adding-a-verifypy-script

**Comment by glicht** [comment]
@ohaim1008 @bakatzir please go over this PR. You should have only one docker image.

**Comment by ohaim1008** [comment]
We will have only one, there is an issue with the packages the docker needs
for sqlalchemy for Microsoft SQL, the "regular" one is not supported
anymore and I'm trying to use different one but we have an issue with the
dockerfile that we didn't solve yet, the unneeded docker images will be
deleted and I'll close the PR for know.

בתאריך יום ד׳, 4 במרץ 2020, 09:54, מאת Guy Lichtman ‏<
notifications@github.com>:

**Pull request closed without merging**
