### PR TITLE
Upgrade golang

### PR DESCRIPTION
**Pull request by liorblob**
## Status
In Progress

## Description
Upgrading golang version

### CODE REVIEW

**Review by agamm — CHANGES_REQUESTED** [review]
@liorblob did you check all of the builds and schedules with this new version?
@orius123 @yardensade What do you think?

**Comment by liorblob** [comment]
@agamm normal + AWS build, i'll run more builds to make sure, but this is just the PR for the docker image.

**Comment by orius123** [comment]
If normal and AWS passes it should be fine
Maybe test engines as well

**Comment by agamm** [comment]
> @agamm normal + AWS build, i'll run more builds to make sure, but this is just the PR for the docker image.

The docker image is the underlying env for all the builds, that is why I'm asking.

**Comment by liorblob** [comment]
builds look fine. let's merge the server PR first and see everything is ok. we can merge this later.

**Comment by liorblob** [comment]
@agamm The image was used in the server build for a couple of days. Should we merge?

**Comment by agamm** [comment]
> @agamm The image was used in the server build for a couple of days. Should we merge?

I'm in a vacation atm, if urgent double check with eliya and sade :)

**Comment by liorblob** [comment]
Not urgent, but I think you need to explicitly approve because you requested changes :)

**Comment by yardensade** [comment]
We can merge as far as I'm concerned.
@glicht can dismiss the request changes if needed.

**Comment by agamm** [comment]
> @agamm The image was used in the server build for a couple of days. Should we merge?

Yes, if it looked good.

**Comment by liorblob** [comment]
@agamm you need to approve :)

**Review by agamm — APPROVED** [review]

**Pull request merged**
