### PR TITLE
Reversinglabs

### PR DESCRIPTION
**Pull request by ivukovicRL**
## Description
Added rl-threat-hunting Python package
Bumped Docker image version to 2.0.0

### CODE REVIEW

**Review by barchen1 — COMMENTED** [review]
Thank you for your contribution!
Please follow the instructions here: https://github.com/demisto/dockerfiles/pull/6288#issuecomment-901875919 and make sure the image fits your needs.
Let me know if you need help

**Comment by ivukovicRL** [comment]
> # Docker Image Ready - Dev
> Docker automatic build at CircleCI has completed. The docker image is available as an artifact of the build.
> 
> Follow the output from the build on how to load the image locally for testing:
> 
> Docker image [devdemisto/reversinglabs-sdk-py3:2.0.0.23984] has been saved as an artifact. It is available at the following link:
> https://23984-161347705-gh.circle-artifacts.com/0/docker_images/devdemisto_reversinglabs-sdk-py3:2.0.0.23984.tar.gz
> 
> Load it locally into docker by running:
> 
> ```
> curl -L "https://23984-161347705-gh.circle-artifacts.com/0/docker_images/devdemisto_reversinglabs-sdk-py3:2.0.0.23984.tar.gz" | gunzip | docker load
> ```

Hi, how do we point to local image once it is loaded?

**Comment by barchen1** [comment]
Are you in the DFIR community? Is this your username `Igor Vuković`?

**Comment by barchen1** [comment]
@ivukovicRL Tested the new docker image and confirm that everything works for him.

**Pull request merged**
