### PR TITLE
Pykafka - changed docker to use Pykafka's master branch and not release

### PR DESCRIPTION
**Pull request by guykeller**
## Status
Ready

## Description
This change will fix a bug regarding lz4 coding, which was fixed in Pykafka's master but never released.

### CODE REVIEW

**Comment by ronykoz** [comment]
Let's add git to the docker file to make the build pass

**Comment by glicht** [comment]
We should pin to a specific commit. I will to a small update to the PR.

**Comment by glicht** [comment]
@guykeller don't add entries directly to the Pipfile file. You should run in the pykafak directory:
```
pipenv install xxhash
```
That way the Pipflle.lock file is updated too.

**Comment by guykeller** [comment]
Closing since this is obsolete.

**Pull request closed without merging**
