### PR TITLE
Add nicknames package to xpanse-ml-ev2 image

### PR DESCRIPTION
**Pull request by kball-pa**
## Status
In Progress

## Related Content Pull Request
Related PR: not yet open

## Description
This is my first contribution to this repo. This PR aims to add the `nicknames` package as a dependency to the `xpanse-ml-ev2` docker image. This dependency is required for an upcoming update to an automation in the CortexAttackSurfaceManagement pack.

Test plan: build development image using CI/CD on PR, reference dev image locally in tests for updated automation, then merge if tests pass?

### CODE REVIEW

**Comment by kball-pa** [comment]
Hi @JudahSchwartz , do you know if there's a way to use the development image that was published by CI/CD while running `demisto-sdk lint` locally for a particular automation? cc @ShacharKidor

**Comment by JudahSchwartz** [comment]
yeah you can run 
`curl -L "https://output.circle-artifacts.com/output/job/b81274b1-def6-4c6c-bc0e-81ab17918e43/artifacts/0/docker_images/devdemisto_xpanse-ml-ev2:1.0.0.65079.tar.gz" | gunzip | docker load
`
This command you can find in the end of the build under the build images step
it should print the tag you added, copy that tag and set the dockerimage tag in the yml to that tag. let me know if you need help along the way

**Comment by kball-pa** [comment]
I did that but it fails with 
```
Failed to get python version from docker hub for image devdemisto/xpanse-ml-ev2:1.0.0.64858: Failed to get docker image digest: {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":"unknown tag=1.0.0.64858"}]}
```
It seems like it's looking for the tag in the dockerhub but I think because I'm contributing via an external fork it's not published there

**Comment by JudahSchwartz** [comment]
@kball-pa what failed? Lint or installing the docker?
@dorschw looks like a devbug

**Comment by JudahSchwartz** [comment]
@kball-pa thanks, theres a bug open to take care of this. In the meantime, we can merge to a branch so that an image gets uiploaded to dockerhub, which will solve the issue, or we can merge to master if youre confident in the changes in dockerfiles

**Comment by kball-pa** [comment]
great, thanks @JudahSchwartz! I feel confident about the changes, we can merge to master.

**Comment by kball-pa** [comment]
@JudahSchwartz @dorschw can we merge to master?

**Comment by kball-pa** [comment]
Actually I decided to close this PR for now -- for the sake of simplicity/time constraints, I can move forward with the existing docker image and just have slightly reduced functionality on the content side. 

We can come back to this PR later as follow-up work. Thanks all for the help!

**Pull request closed without merging**
