### PR TITLE
New Docker image for taxii2 client using stix2 and taxii2-client for …

### PR DESCRIPTION
**Pull request by aburt-demisto**
…Python

## Status
Ready

## Related Issues
N/A

## Description
New Docker container that includes the stix2 and taxii2-client libraries for Python

### CODE REVIEW

**Comment by aburt-demisto** [comment]
@glicht, I hope this PR looks correct. I had to use python3-deb for it as there are no libraries for stix2 and taxii2-client (Python) available.

**Comment by glicht** [comment]
Hi @aburt-demisto let's rename the folder to simply: `taxii2`

Also let's base the image on alpine based docker image.

**Comment by aburt-demisto** [comment]
@glicht, Sure, sounds great to me. I'll keep an eye out for dev image to test with. Do you want me to change to Alpine, or can you?

**Comment by aburt-demisto** [comment]
Closing request as I will re-submit using Alpine Linux

**Pull request closed without merging**
