### PR TITLE
|Added Docker file to integrate with Group-IB

### PR DESCRIPTION
**Pull request by Kchekh**
## Status
Ready

## Related Content Pull Request
Related PR: https://github.com/demisto/content/pull/35663

## Description
Add a Docker file for better integration with the services provided by Cortex

### CODE REVIEW

**Comment by thefrieddan1** [comment]
Hi @Kchekh 
Thank you for your contribution. 
Is there a content PR to go along with this dockerfiles pr?
Thanks

**Comment by Kchekh** [comment]
> Hi @Kchekh Thank you for your contribution. Is there a content PR to go along with this dockerfiles pr? Thanks

Hi @thefrieddan1 

While we haven't created a pr yet, we will do so near the end of the integration update. For now, we need to update the docker image

Thanks

**Comment by Kchekh** [comment]
Hi @thefrieddan1
I successfully created and linked it here

**Comment by thefrieddan1** [comment]
> Hi @thefrieddan1 I successfully created and linked it here

Thanks.
Can you please use python 3.11 in docker/group-ib-integrations/Pipfile

**Comment by Kchekh** [comment]
> > Hi @thefrieddan1 I successfully created and linked it here
> 
> Thanks. Can you please use python 3.11 in docker/group-ib-integrations/Pipfile

I would like to retire the current configuration as other types of it have caused errors. Everything works now

**Comment by Kchekh** [comment]
Hi @thefrieddan1 
Can you please do the review?

**Comment by thefrieddan1** [comment]
> Hi @thefrieddan1 Can you please do the review?
Hi @Kchekh After reviewing your contribution, we have decided it is a better use case to add the cyberintegrations under 
`vendors SDK`
Thanks

**Comment by Kchekh** [comment]
Hi @thefrieddan1,
We thought about it and decided it would be a good idea. Does it require anything from me?
Thanks

**Comment by thefrieddan1** [comment]
Hi @Kchekh, 
I have added cyberintegrations as part of SDK verndors.
Closing this PR.
Thanks

**Pull request closed without merging**
