### PR TITLE
New Scoutsuite Docker Image

### PR DESCRIPTION
**Pull request by apekarovsky**
## Status
Ready

## Description
Scoutsuite new docker Image.

### CODE REVIEW

**Comment by apekarovsky** [comment]
Hi @glicht , could you please help with this one?

**Review by glicht — CHANGES_REQUESTED** [review]
Please provide link to the integration PR. Need to review how scoutsuite is being used.

**Comment by glicht** [comment]
@apekarovsky is this still relevant?

**Comment by apekarovsky** [comment]
No, can be deleted.
Thanks.

**Pull request closed without merging**
