### PR TITLE
xsoar-tools - bump demisto-sdk version to 1.3.0

### PR DESCRIPTION
**Pull request by Itay4**
## Status
Ready

## Description
bump demisto-sdk version

### CODE REVIEW

**Comment by glicht** [comment]
Note that you are bumping here also other deps such as mypy.

**Comment by glicht** [comment]
We probably are better using an exact version in Pipfile for the deps we use in the build (at least the linters). See: https://github.com/demisto/content/blob/master/dev-requirements-py3.txt

**Review by glicht — APPROVED** [review]

**Comment by Itay4** [comment]
@glicht please see my last changes
the common server scripts are required for the lint to avoid false positives about missing funcs

**Comment by glicht** [comment]
> @glicht please see my last changes
> the common server scripts are required for the lint to avoid false positives about missing funcs

I think it is better to download just the relevant files using wget and the raw url. For example: https://raw.githubusercontent.com/demisto/content/master/Packs/Base/Scripts/CommonServerPython/CommonServerPython.py

**Comment by Itay4** [comment]
@glicht modified to use wget

**Review by glicht — APPROVED** [review]

**Pull request merged**
