### PR TITLE
Add `json2html` to py3-tools

### PR DESCRIPTION
**Pull request by nikstuckenbrock**
## Status
Ready

## Description
Just created a simple container containing the [`json2html`](https://pypi.org/project/json2html/) package as a dependency.
## Content PR:
https://github.com/demisto/content/pull/35633

### CODE REVIEW

**Comment by JudahSchwartz** [comment]
hey @nikstuckenbrock, thanks for the contribution! do you have a content PR to go along with this?

**Comment by nikstuckenbrock** [comment]
Hey @JudahSchwartz ,

nope. :)

**Comment by JudahSchwartz** [comment]
@nikstuckenbrock if thats the case we dont tend to merge in new images that we will need to maintain here if theres no content contribution that goes along with it.

**Comment by nikstuckenbrock** [comment]
@JudahSchwartz I could also provide an automation using the image if that helps?

**Comment by JudahSchwartz** [comment]
absolutely =)

**Comment by nikstuckenbrock** [comment]
@JudahSchwartz Is there a pack that takes utility scripts/automations? Or is this content of the base back?

**Comment by JudahSchwartz** [comment]
@thefrieddan1 can you help with understanding where the right place to put this script is? Also @nikstuckenbrock can we add this library to py3-tools docker image instead of creating one just for this 1?

**Comment by thefrieddan1** [comment]
@nikstuckenbrock I suggest adding a script to CommunityCommonScripts
As well as closing this PR and adding the library to py3-tools docker image as @JudahSchwartz suggested.
Thanks.

**Comment by nikstuckenbrock** [comment]
Created a PR [#35633](https://github.com/demisto/content/pull/35633) for the new script.

**Review by thefrieddan1 — APPROVED** [review]

**Review by shmuel44 — APPROVED** [review]
Nice!

**Pull request merged**
