### PR TITLE
Add GitLab Image

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Status
Ready

## Description
Adding image containing python-gitlab package

### CODE REVIEW

**Comment by tomneeman151293** [comment]
@dantavori @ShahafBenYakir 
I am not 100% sure the way i added is the correct (tried to follow the guide). Would love to have this checked well if you can

**Comment by tomneeman151293** [comment]
@ShahafBenYakir @dantavori Pinging you again regarding this image PR so I can continue developing the GitLab content bot

**Comment by ShahafBenYakir** [comment]
@tomneeman151293 I am confused I thought we are working with the exsisting integration which uses API

**Comment by tomneeman151293** [comment]
Closing this PR as we decided to implement GitLab commands with HTTP call and not python-gitlab library

**Pull request closed without merging**
