### PR TITLE
Using devo-sdk

### PR DESCRIPTION
**Pull request by anas-yousef**
## Status
In Progress

## Related Content Pull Request
Related PR: https://github.com/demisto/content/pull/33950

## Related Issues
Related: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

### CODE REVIEW

**Comment by anas-yousef** [comment]
@JudahSchwartz
Updated the docker image to use the package **devo-sdk** instead of **devodsconnector**, as per the partner's request: https://github.com/demisto/content/pull/33950
I checked and the package **devodsconnector** was only used in  [Devo_v2.yml](https://github.com/demisto/content/blob/master/Packs/Devo/Integrations/Devo_v2/Devo_v2.yml)

**Comment by JudahSchwartz** [comment]
@kgal-pan is this work we should be doing? not the parner?

**Comment by edik24** [comment]
@JudahSchwartz it should be done by partner.
But it's ok to help them, if they're having some issues with that.

@anas-yousef they didn't want to do that by themselves?

**Review by JudahSchwartz — APPROVED** [review]
relying on @anas-yousef  to make sure pandas is needed

**Comment by anas-yousef** [comment]
> relying on @anas-yousef to make sure pandas is needed

https://github.com/demisto/content/pull/33950#issuecomment-2063609921
https://github.com/demisto/content/pull/33950/files#diff-98dc9e9102066408b9e875f881b09e66f7c5337449452c2c4890cbff9e587237R179

**Comment by anas-yousef** [comment]
> @JudahSchwartz it should be done by partner. But it's ok to help them, if they're having some issues with that.
> 
> @anas-yousef they didn't want to do that by themselves?

@edik24 They asked for my assistance regarding updating the docker image.

**Pull request merged**
