### PR TITLE
Create a dockerfile with adal library

### PR DESCRIPTION
**Pull request by orlichter1**
## Status
In Progress

## Related Issues
related: https://github.com/demisto/etc/issues/28446

## Description
Needed a docker with adal library

### CODE REVIEW

**Comment by glicht** [comment]
Let's name the image ms-auth. 

Also why are you using debian and not alpine?

**Comment by orlichter1** [comment]
@glicht 👍  No problem, will rename.
We're using Debian as alpine raised some sort of issue that can be seen [here](https://app.circleci.com/pipelines/github/demisto/dockerfiles/8204/workflows/fcc54f01-e97e-47de-95e7-2204e6eb1e8d/jobs/14086)

**Comment by glicht** [comment]
> @glicht 👍 No problem, will rename.
> We're using Debian as alpine raised some sort of issue that can be seen [here](https://app.circleci.com/pipelines/github/demisto/dockerfiles/8204/workflows/fcc54f01-e97e-47de-95e7-2204e6eb1e8d/jobs/14086)

As there is a dependency on cryptography you should use demisto/crypto which is alpine based. See for example the teams dockerfile.

**Comment by glicht** [comment]
@orlichter1 what's the status here?

**Comment by orlichter1** [comment]
@glicht Not needed anymore - deleting the PR and branch

**Pull request closed without merging**
