### PR TITLE
Titaniam Quadra docker image

### PR DESCRIPTION
**Pull request by fadil-mesic**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
related: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

### CODE REVIEW

**Review by anara123 — CHANGES_REQUESTED** [review]
Your build failing on the following message.
```
grep: /home/circleci/project/./docker/quadra/build.conf: No such file or directory
==============================
Failed verifying docker config for: [/home/circleci/project/./docker/quadra] in dependabot/.config.yml
To add the config run: ./docker/add_dependabot.sh docker/quadra
```

You need to run `./docker/add_dependabot.sh docker/quadra` that will create `docker/quadra/build.conf` file

**Comment by anara123** [comment]
@fadil-mesic also add `verify.py`, see example here https://github.com/demisto/dockerfiles/blob/master/docker/crypto/verify.py
This file will run during the build. The purpose of the file is to make sure the required functionality of in the docker works as expected. So you can try to connect to some service if you want, or to check if the service alive.

**Comment by glicht** [comment]
@anara123 status?

**Comment by anara123** [comment]
We agreed to close this PR for the moment

**Pull request closed without merging**
