### PR TITLE
[TEST] Add base image from gitlab

### PR DESCRIPTION
**Pull request by agamm**
## Status
In Hold (Used to help gitlab ci with images - testing)

### CODE REVIEW

**Comment by glicht** [comment]
@agamm can we close this?

**Comment by agamm** [comment]
> @agamm can we close this?

Not at all atm, we are using this as the base image for the gitlab-ci. 
We could start a migration to a more production ready docker image if it is urgent from your side.

**Comment by glicht** [comment]
Change the name of the image (without test) and add secondly=true to build.conf and we can then merge.

**Comment by agamm** [comment]
Close this if https://github.com/demisto/dockerfiles/pull/3301 merged.

**Pull request closed without merging**
