### PR TITLE
Added new docker image for vcrpy

### PR DESCRIPTION
**Pull request by ChanochShayner**
## Status
Ready

## Related Issues
related: https://github.com/demisto/content/pull/10830

## Description
Added new docker image for vcrpy liberty, for partner contribution.

### CODE REVIEW

**Comment by guykeller** [comment]
@ChanochShayner Just making sure you haven't missed the fact that the build is failing

**Review by glicht — CHANGES_REQUESTED** [review]
Something is wrong with .dependabot/config.xml . Not clear why there are so many changes there.

**Comment by ChanochShayner** [comment]
> Something is wrong with .dependabot/config.xml . Not clear why there are so many changes there.
@glicht It seems that the necessary changes have been added (as in other PRs)
One package_manager: python and one - package_manager: docker

**Comment by glicht** [comment]
> > Something is wrong with .dependabot/config.xml . Not clear why there are so many changes there.
> > @glicht It seems that the necessary changes have been added (as in other PRs)
> > One package_manager: python and one - package_manager: docker

Ok. I guess there was something wrong with the displayed diff. It looks good now.

**Comment by ChanochShayner** [comment]
I close the PR because docker image is not generated for Partner in this case.

**Pull request closed without merging**
