### PR TITLE
ansible-runner/ansible 2.9.12

### PR DESCRIPTION
**Pull request by SergeBakharev**
## Status
In-Progress

## Related Issues
N/A

## Description
Required container image for my Automation Rising 2020 SOAR Hackathon submission.

Two Python packages (`ansible`, and it's dependency `docutils`) do not pass verify_licenses.py. However I'm unclear if GPL is a approved OSI license type or not. it is not present in known_licenses.json nor approved_licenses.json. 

My submission does not link to the Ansible python libraries, so I do not believe the GPL Automatic Inheritance applies to my submission (if that was a concern), and even if it did I intend on making my hackathon submission available to the community. 

Using the python ansible module is merely a convenient way to get a specific version of Ansible install into the container that I have tested my work against. The Debian Buster ansible package is quite a few versions out of date from what I would like to use, but the Debian Bullseye is one patch level ahead. If use of the ansible python module is not allowed, I am happy to use the Debian ansible package as an alternative.

### CODE REVIEW

**Comment by glicht** [comment]
@SergeBakharev Thanks for your submission. Please accept our CLA so we can proceed. See the comment: https://github.com/demisto/dockerfiles/pull/2772#issuecomment-700571555

**Comment by SergeBakharev** [comment]
@glicht Not sure it is saying that the CLA is not signed. I signed it when I submitted the PR, and if I re-visit the link it shows as signed for me. Is there something else I need to do?

https://imgur.com/a/VaeTSgk

**Comment by glicht** [comment]
@SergeBakharev your commit is not linked to your github user. See instructions here on how to fix: https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by SergeBakharev** [comment]
Thanks @glicht . I've resubmitted the PR with the a fresh commit that is properly linked!

**Pull request closed without merging**
