### PR TITLE
Bump octoxlabs 0.4.4 to 0.5.0 in /docker/octoxlabs 

### PR DESCRIPTION
**Pull request by ogulcanhero**
## Status
Ready

## Related Content Pull Request
This will be added after this image deployed to demisto docker hub organization.

## Description
Update octoxlabs package to 0.5.0
Also details: https://github.com/octoxlabs/py-octoxlabs
Internal PR: https://github.com/demisto/dockerfiles/pull/34709

### CODE REVIEW

**Comment by samuelFain** [comment]
Hi @ogulcanhero, thank you for you contribution!
We had some technical issues with Github that have affected our ability to properly review the PR.
I'll review your PR shortly. Thank you for your patience.

**Review by samuelFain — CHANGES_REQUESTED** [review]
Hi @ogulcanhero, I have two questions:
- I see that only the `docker/octoxlabs/Pipfile.lock` file has changed in this PR. However, changes to the Pipfile.lock file typically result from modifications to the Pipfile itself, followed by running a command like `pipenv lock`. I feel like the changes to the Pipfile are missing. Please let me know if I am misunderstanding your intentions.
- Generally, contributions to the `dockerfiles` repository are accompanied by a corresponding PR in the content repository. While this is not mandatory, if there is a related PR in the content repository, please let me know about it.

**Comment by ogulcanhero** [comment]
Hi @samuelFain, 

Thank you for your review. 
Yes, that's right, I ran the pipenv update command and wanted the lock file to change because I want the octoxlabs module that I will use in the "content" to be in the 0.5.0 version, so I think just updating pipenv will be enough.

 Have a nice day.

**Comment by samuelFain** [comment]
@ogulcanhero Thank you for your clarification.
Due to a technical issue we had with Github, can you please re-sign the [Contributor License Agreement](https://cla-assistant.io/demisto/dockerfiles?pullRequest=34467)? I believe It is currently blocking the PR from running all its tests (Github actions). Also please merge the the changes from the base branch if needed.
Thank you!

**Comment by ogulcanhero** [comment]
Hi @samuelFain,

I re-signed the CLA. License fyi.

Thank you!

**Review by samuelFain — APPROVED** [review]

**Comment by ogulcanhero** [comment]
Hi @samuelFain, 
Auto merge is not possible due to verify. How can we solve this?
Thank You!

**Comment by samuelFain** [comment]
> Hi @samuelFain, Auto merge is not possible due to verify. How can we solve this? Thank You!

Hi @ogulcanhero
I'm working on it, apologies on the delay.

**Comment by samuelFain** [comment]
@ogulcanhero We are currently handling a technical issue which prevents the `ci/gitlab/gitlab.xdr.pan.local` Github action to run on contribution PRs in this repository.

To avoid delaying the merging of changes in this PR, I have manually opened an internal PR https://github.com/demisto/dockerfiles/pull/34709 with your changes and merged it.

Please do not close this PR, as we will use it to verify our fix for this issue. However, you can consider your contribution as merged at this time. 

Thank you for your understanding.

**Comment by ogulcanhero** [comment]
Thank you @samuelFain, I'm sorry to bother you, good job.

**Pull request closed without merging**
