### PR TITLE
added armorblox-python-sdk package

### PR DESCRIPTION
**Pull request by SamhithaTatipalli**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
Related: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

### CODE REVIEW

**Comment by SamhithaTatipalli** [comment]
I was not able to download the build docker image artifact files. What is the ETA for this PR to get approved?

**Comment by SamhithaTatipalli** [comment]
Hi Team,

I am unable to download the artifact. Please help.

Regards,
Samhitha.

**Comment by ShacharKidor** [comment]
Hi @SamhithaTatipalli, 
Thank you for contributing this PR!

I would like to better understand the reason for adding this new docker. 
Is this new docker image related to new content added to our content repository? if yes can please add here a comment with a link to the relevant PR in the content repository? 

Thanks in advance.

**Comment by SamhithaTatipalli** [comment]
Hi @ShacharKidor,
 
We already have an integration on Cortex named Armorblox - https://xsoar.pan.dev/marketplace/details/Armorblox. We would want to modify/update this integration and we need our python library to be installed to import and use - this is the reason for this new docker.

Thanks and regards.
Samhitha.

**Comment by ShacharKidor** [comment]
> Hi @ShacharKidor,
> 
> We already have an integration on Cortex named Armorblox - https://xsoar.pan.dev/marketplace/details/Armorblox. We would want to modify/update this integration and we need our python library to be installed to import and use - this is the reason for this new docker.
> 
> Thanks and regards. Samhitha.

@SamhithaTatipalli - Ok great - when you'll open the new PR with the changes in the integration, please be sure to add a comment here with a link to the content PR. 

I'm checking about the above mentioned problem with the docker image artifacts  - will update you soon :)

Thanks.

**Comment by SamhithaTatipalli** [comment]
What is the ETA for this PR to get approved?

**Comment by SamhithaTatipalli** [comment]
@ShacharKidor - What is the ETA for this PR to get approved? Could you please update on this?

**Comment by ShacharKidor** [comment]
> @ShacharKidor - What is the ETA for this PR to get approved? Could you please update on this?

Hi @SamhithaTatipalli, 
I apologize for the delayed response. 
I'm still checking why the link to the docker image (at the top of this PR) is broken, but in the meantime, you can download the archive (docker) from the CircleCI itself:
https://app.circleci.com/pipelines/github/demisto/dockerfiles/25014/workflows/7af2c0e0-b976-4236-a4ab-c4cde9c39a55/jobs/31340/artifacts

[docker_images/devdemisto_armorblox:1.0.0.31340.tar.gz](https://output.circle-artifacts.com/output/job/1eecc366-1017-419b-9da0-27e9c9eec446/artifacts/0/docker_images/devdemisto_armorblox:1.0.0.31340.tar.gz).

Please try to use the devdemisto_armorblox image and test your changes with it - please update me if you encounter any errors. 

This PR will be approved by the reviewer who will review your content PR, so please add a comment with a link to your new PR in the content repository once you open it. 

I'm also available on slack for any further questions.

**Comment by ShacharKidor** [comment]
Hi @SamhithaTatipalli, 
We have fixed the above-mentioned link problem - you can pull our master, merge and push and you'll get the fixed link. 
You can also use the file I sent in my last message, should be the same. 

Please update me if you need any help :) 
Thank you.

**Comment by SamhithaTatipalli** [comment]
Hi @ShacharKidor, 
The docker image which we have created is a third party package, we will be using it in content repo. For that the image has to be in docker hub. If PR is not approved we will not be able to find the image. Please help us with this issue.


Please share your slackid, so that I can connect with you there only for any doubts.

**Comment by SamhithaTatipalli** [comment]
Hi @ShacharKidor ,
The docker image which we have created is the third party package. We will be utilizing this image into our content repo once it is available in docker hub. If the PR is not approved, then we would not be able to find the image and proceed further. Please help us on this issue.

For reference please find the Link: https://xsoar.pan.dev/docs/integrations/docker.

Please share your slackID , so that I will be connecting with you for other clarifications.

Thanks and regards,
Samhitha.

**Comment by ShacharKidor** [comment]
@SamhithaTatipalli - I've sent you a message on slack (my slackID is Shachar Kidor).

**Comment by SamhithaTatipalli** [comment]
@ShacharKidor ,

Sorry! I couldnt find you. Could you tell me your workspace?

**Comment by ShacharKidor** [comment]
This PR is not relevant anymore - the new updated PR is - [8214](https://github.com/demisto/dockerfiles/pull/8214).
Closing the PR.

**Pull request closed without merging**
