### PR TITLE
Upgrade perl and sqlite3

### PR DESCRIPTION
**Pull request by inbalapt1**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
Related: link to the issue

## Description
Upgrade perl and sqlite3 in ml image

### CODE REVIEW

**Review by tkatzir — COMMENTED** [review]
Looking good!
commented.

**Review by tkatzir — APPROVED** [review]
Approved.

**Review by jlevypaloalto — COMMENTED** [review]
Looks good to me 🚀

**Comment by inbalapt1** [comment]
The PR requires a force merge as part of the update is being addressed in the related ticket: [CIAC-12067](https://jira-dc.paloaltonetworks.com/browse/CIAC-12067)

**Pull request merged**
