### PR TITLE
Created rapidfuzz image

### PR DESCRIPTION
**Pull request by KrisRosser**
## Status
Ready

## Related Content Pull Request
Related PR: no related PR. Image for use in custom content.

## Related Issues
Related: no related issues.

## Description
Creation of a image containing rapidfuzz python library. For use by custom automations within xsoar.

### CODE REVIEW

**Comment by eyalpalo** [comment]
Hi @KrisRosser!
Is this part of an existing content contribution? If so, please attach the relevant PR to this one.
Thank you!

**Comment by KrisRosser** [comment]
Hi @eyalpalo,
This is not part of an existing content contribution. Therefore, I have no relevant PR to attach.
Thank you.

**Comment by JudahSchwartz** [comment]
Hey @KrisRosser, are you planning to open a content PR? What is the purpose of this pull request?

**Comment by JudahSchwartz** [comment]
@KrisRosser , `Secondly, (this is the major issue), demisto-sdk validate and lint commands will fail on any content using those images which prevents the content from being pushed to CI/CD pipeline (precommit fails and github actions fail)` 
Which pipeline are you refferring to? This is custom content, correct? 
you can add DO107 to the pack ignore, this should prevent this issue from demisto-sdk validate, then the customer can push this image to their own dockerhub account to easily have pulled by the machines using it.

We dont generally support pushing customer's images to our dockerfiles repo unless there is a content contribution to go along with them

Let me know if this helps. Im going to close this pr for now, feel free to reopen

**Pull request closed without merging**
