### PR TITLE
Initial commit of image xpanse-ml-ev2

### PR DESCRIPTION
**Pull request by ptoman-pa**
## Status
Ready

## Related Content Pull Request
No content PR yet (in testing)

## Related Issues
No issue yet (in testing)

## Description
I need an image that supports sklearn and google storage as part of work on Cortex Xpanse Ev2. With a devdemisto image, I can continue development on a script. I have not worked in this repo before.

### CODE REVIEW

**Comment by johnnywilkes** [comment]
@ShacharKidor , tagging you here per our conversation

**Comment by ShacharKidor** [comment]
Hi @ptoman-pa, 
Thanks for your contribution! :)
Is there any related content PR that requires this new docker image? (I would like to link it to this one).

**Comment by ptoman-pa** [comment]
Hi @ShacharKidor, thank you for your review! No, there is no content PR yet. The content PR is not ready yet.

**Comment by glicht** [comment]
Updated the branch with master to get the build running.

**Review by glicht — APPROVED** [review]

**Pull request merged**
