### PR TITLE
adding docker image for dl-languages

### PR DESCRIPTION
**Pull request by lperryp**
## Status
Ready/In Progress/In Hold (Reason for hold)

## Related Issues
related: link to the issue

## Description
Creating a separate docker image for dl which supports languages

### CODE REVIEW

**Comment by lperryp** [comment]
@glicht - the validation fails because we use our own library which the script can't find a licence for it

**Comment by glicht** [comment]
@lperryp is this still relevant following the discussion we had?

**Comment by lperryp** [comment]
> @lperryp is this still relevant following the discussion we had?

@glicht yes, but will update base image to new docker that we built

**Comment by lperryp** [comment]
@glicht the I get an exception 
`Exception: es-core-news-sm: no approved license found for license: License: GPL` 
It's a download of a model from a package called `spacy` that we use in other dockers, can we overcome this?

**Review by glicht — APPROVED** [review]

**Pull request merged**
