### PR TITLE
Updated poetry.lockfor devo image

### PR DESCRIPTION
**Pull request by Shellyber**
## Status
Ready

## Related Content Pull Request
Related PR: https://github.com/demisto/content/pull/24842

## Description
Updated the packages because of the following issue: [AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'](https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss)

### CODE REVIEW

**Comment by ShahafBenYakir** [comment]
I am confused, why did we added cryptography to this image as a fix?

**Comment by Shellyber** [comment]
We didn't, It already existed in the docker image.
But the latest update that happened upgraded the version, which broke the integration
I just reverted back to the previous version

**Comment by JudahSchwartz** [comment]
@Shellyber if we need the version locked we also need to specify it in the dependabot config, otherwise dependabot will upgrade it anyway

**Comment by JudahSchwartz** [comment]
@Shellyber we cant make the fix on the integration side instead?

**Comment by Shellyber** [comment]
@JudahSchwartz No, this is a partner integration so I can't really fix it locally
Also when trying to update all (so we won't need to lock it) it caused a different problems with their SDK
So the best thing is to lock the version

**Pull request closed without merging**
