### PR TITLE
[Axonius Dockerfile] Bumping axonius api client version

### PR DESCRIPTION
**Pull request by bryce-ax**
## Status
Ready

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
https://github.com/demisto/content/pull/29625

## Description
Upgrading Axonius API Client due to major changes in API Client and Axonius Platform.
Corresponding Content PR will be linked.

### CODE REVIEW

**Comment by bryce-ax** [comment]
Hey @RotemAmit, silly question, but how do I know what version to bump the dockerfile to in content?

**Comment by bryce-ax** [comment]
@RotemAmit 
https://github.com/demisto/content/pull/29625

**Comment by bryce-ax** [comment]
@RosenbergYehuda I'm hoping we can get this merged asap. Cheers!

**Comment by RosenbergYehuda** [comment]
Hello @bryce-ax ,
Apologies for the delay in merging your new image contribution. In order to move this forward, I need you to complete the CLA (Contributor License Agreement) form. As you can see, there is a GitHub Actions step blocking the merge until the CLA is submitted.

Please let me know once you have submitted the CLA form, and I will do my best to get your image merged as soon as possible. Thank you for your contribution!

**Comment by bryce-ax** [comment]
CLA has been completed

**Review by RosenbergYehuda — APPROVED** [review]

**Pull request merged**
