### PR TITLE
Rasterize includes url bar in screenshot

### PR DESCRIPTION
**Pull request by wissamg**
## Status
n Progress

## Related Content Pull Request
Related PR: link to the PR at demisto/content

## Related Issues
Related: link to the issue

## Description
Adding url bar to screen shot

### CODE REVIEW

**Comment by glicht** [comment]
Is there a PR in Content?

**Comment by yaakovpraisler** [comment]
@glicht - Not yet, I will probably open later today.

**Review by yaakovpraisler — APPROVED** [review]

**Comment by glicht** [comment]
@wissamg is tessarect used only for testing? If so, we shouldn't add it.

**Comment by wissamg** [comment]
> 

yes, it is for testing only and we are trying a different way to install it without affecting the release version. (using the install.sh script).

**Comment by wissamg** [comment]
> @wissamg is tessarect used only for testing? If so, we shouldn't add it.

@glicht Can you please approve this, it is ready!.
thanks

**Comment by glicht** [comment]
> @glicht - Not yet, I will probably open later today.

Please share the PR

**Comment by yaakovpraisler** [comment]
> > @glicht - Not yet, I will probably open later today.
> 
> Please share the PR
@glicht - https://github.com/demisto/content/pull/20380/
@עךן

**Pull request merged**
