### PR TITLE
Domaintools

### PR DESCRIPTION
**Pull request by wesleya**
## Status
Ready

## Related Content Pull Request
Related PR: https://github.com/demisto/content/pull/29474

## Related Issues
N/A

## Description
Add a new image for use in new version 2.0 PR of the DomainTools Iris Pack

### CODE REVIEW

**Comment by wesleya** [comment]
Do you have a recommendation for fixing the failed ci step? The error sounds like it has something to do with the version of python we are using `3.10.13`? But this is the default the came when we started the image using the `./docker/create_new_docker_image.py -p three --pkg domaintools-api domaintools` command. This image also seems to work fine when we build for local testing. I've tried a few changes with no luck so far, any guidance is appreciated, thank you!

**Comment by JudahSchwartz** [comment]
@wesleya seems like this error is being caused by having "3.10.13" in the pipfile, but it isnt installed on the system. Then the prompt asking to download the version is ignored, this is a bug and we'll fix it soon
I think setting the version to "3.10" in the pipfile and relocking should do the trick

**Comment by wesleya** [comment]
thank you for the guidance there @JudahSchwartz, I believe we've made the necessary update. Lmk if there's anything else needed, thank you

**Comment by MichaelYochpaz** [comment]
@wesleya [We're working on creating a Docker image containing multiple lightweight SDK packages of different vendors](https://github.com/demisto/dockerfiles/pull/19658) (instead of unnecessarily creating a separate Docker image for each one).
We've added your package (`domaintools-api`) there.

Once it's merged and the Docker image is available, I'll close this PR (keeping it open for now in case we will unexpectedly need it) and give you an update.

**Comment by wesleya** [comment]
@MichaelYochpaz that all sounds great, I'll keep an eye out for when for when that image is available. Thank you for the update.

**Comment by MichaelYochpaz** [comment]
>  @MichaelYochpaz that all sounds great, I'll keep an eye out for when for when that image is available. Thank you for the update.

@wesleya It was actually already merged yesterday shortly after I sent the message, you can see the new Docker image [here](https://hub.docker.com/r/demisto/vendors-sdk).

Could you please confirm that this Docker image works fine with your pack's integrations & scripts, and update your other Content PR with this Docker if it does? Please let me know if it does and I'll close this PR.

Feel free to also message me on the DFIR Slack if you've got any questions / need help.

**Comment by wesleya** [comment]
@MichaelYochpaz ah yes I see it. The `demisto/vendors-sdk` image seems to work as expected with our app. I've updated the content PR with this image, feel free to close this PR. Thank you!

**Pull request closed without merging**
